server {
    listen 80;
    server_name stockvn.online www.stockvn.online;
    
    # Tự động chuyển hướng từ HTTP sang HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl; # Lắng nghe cổng 443 với SSL
    server_name stockvn.online www.stockvn.online;

    # Đường dẫn tới chứng chỉ (đã được mount từ Secret vào /etc/nginx/certs)
    ssl_certificate     /etc/nginx/certs/tls.crt;
    ssl_certificate_key /etc/nginx/certs/tls.key;

    # Các cấu hình bảo mật SSL tốt nhất
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Chuyển tiếp tới auth-service
    location /api/auth/ {
        proxy_pass http://auth-service:8080/; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme; # Quan trọng để Backend biết là HTTPS
    }

    # Chuyển tiếp tới forum-service
    location /api/forum/ {
        proxy_pass http://forum-service:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}