apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: docker.io/tuongndb1609/auth-service
  newName: docker.io/tuongndb1609/auth-service
  newTag: 1c691970d8d1b38124b4dc19eeef9fd4ee24861d
