apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: docker.io/tuongndb1609/auth-service
  newName: docker.io/tuongndb1609/auth-service
  newTag: cb22e9762865c978f9a6d57d9c7a448d9aecdfc4
