apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account-trigger
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-account-trigger-role
subjects:
  - kind: ServiceAccount
    name: service-account-trigger
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin