{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "forum-secret",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "forum-secret",
        "namespace": "default",
        "creationTimestamp": null
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "POSTGRES_DB": "AgA3Kt1jdV3PEBCUsAB4Q1FxnXD0FnHwr5XCEEc/E4ur8oV8MW3DRVUi7ufRrmwe8GbG4fBx6GkaRsygt+bEyG3d5/mrY4aPmtsNMbEn0Hg4VV9nREb00yzTOGG0J+z572Lik97ldAIPVHhqXSKPU6jQUlR5jgTYutgW+oL7XydKPvCKdRD0znsitCdya7oKeACoBEiH8L6Mv0y3SbINdW8G4AA6qSolOno4FKbfzgvTGr4GFjIeYZ2EJrlwymxBGKX7mlFDbZZXLwUd9qf5e0BUgyzAp1aNOiFuBiZGnwa9zEMAYEXzTB+mZn+wjfrN4SFt/kl7Ey4JMOiysaHZDQzxAw8SKV8uMHBmloNvedpn9HOMvaGC6qVrn2PF0HTnVNzyhigQECjNJtp+ukIo76N58VEZAn0y3UIqqjIlE9E5I9TsOhUuWm2BwIj13plZO9G2kHLq1igJ8D1iZoI8sNejC7ug6PtoaIsMiHMVFnHJjq4USRWO2u6VmDRgPutsN3w4f5tacqMNz07k6GOL1dCGVTlqGR2Er47ToWTOx0FcMP2PJ2nPzzZtAB5P57p7wHaKcaCWAaxPP0fot1BUjmvgOYiTDwsOlZ+7LWvbB2jW0yLSegfUIhzzqDYEqJxunm/NP8/BrS8wVuSYLJziQJZVeZapw80irzp02pw/J6ehHAUIEdRljBZFvplLkyo5MH8EjxM3drgtCQ==",
      "POSTGRES_PASSWORD": "AgBgGYG1/QM56Pt4rZMK/209EW62zElDLU4zKkwiwqNLeyF5QBdp3NlVFJVxM2Sa92fTbqvtnvFA/FLOXbushHLQ0FZiXDcKpqNATruRu8EGaXdAHXLYHW3KKrcVlD6/bXjc9ojxwHtf/idzsmOGG+Gh8wtWqqEeIlKN044yeawLrJYYd0BOYrHVdLWiv5QM2A44uTlgj77TWBhBlVVhK2KMgut17LYGnMGduTIzhKO//OHcngVORbuzZuQQFSxyGFCNdwkGaagG0zJ3bZOqqHPgc9zI1eXQNQkoRMVyX5VDb4R/ArjkThUZ6fhd4q0j+H45lwl2ohy9rehTQUvgHqMiVYDcg9MVHwHrd+mfFGvbkZpJYf/vT462JyAvLVtvjE0uz7xm3K2LWJEcdF6CWRMzodw/jvBj2l+sdbiAMzeLlfr22WLuPxZuZbdxO98axbRnyV2MpRf3lSggKqpWyAzBeDqLpERz1Pp/GIycbzhzsoEpt7ELOIndGxrF7AAa/CZp+EL/5XxWuFOZVOjxKlsFM3jzs/760+e5dITxXW41G/49cEDpxhOjR1UAsJ4NZqrcOlgM7PLCr6cuA7RWWI4D/yYuhAo0S6mydlrW/z4TmqfxEl24WxA5u/V2dOPg1cPxkfY5o3BOMvhQTusk5YVnAVtgqXVa3Hb7OoWvoyV4yHZ48yL0H6j0jDd/OZOmIBiCvoBG/KaD3Q==",
      "POSTGRES_USER": "AgAIomoaCvZH+u1u6Z/9IcxY8p6fKMTmTH2lLk67l3iKnPMX7PU4+eAKQMSa06NCLBymgZdMLi2ml5F4q48lth9Xh9MFMDWDC2eYO9A4d8FNIfVOLplcCLzGscKh3zRXi8uQzYu81fBQBsq8/xwt05RlLjHwmlKSQFIPtrcPaWsXn8j6NG0b2Ctvn+/5rXkwMPHiU6YaQuMAjqQ41t9LddPxBXFzGVUJAMZKzPkVPVPiAJ881qrP8FPta6Rudnp78m5JKgdnSKGzSpZh1OP0LV2g2roFngxw4fssdKPb4qPBksqZASE6WpUXY0orumtW5iba8QHc6Na8ZxdG/kjy++VA8VTEzXBiEvFFjCYmeWS4dmqUMFfTOgHAQhUtPyT6ObOQXQhOtME0NlcD2hStEgCRrnBmQrjg245KHeG4T+KfRZmuAXvkL/32zfKQ8wJepLcUR+hjMttgrEGrPfSciFnFpE+4I53+p//OuAJv6ZV3DFBIYIXH4tve8pOQn0iHP9EZy9x4aUKdQwIc7VoOrD0P/J5bwxunflmBy5DSoX06gVvNbyNzFntnU5QEOR5aG/ZKHkdUkURh643MK2RcBQGDL5qY2cuwy3RjcNVgEuGluQfOQYJBiVWrMFiaJOWFB1xlqO3MfscFOB5kwb7g8wn6ZJIoiKQ7OgrHvV8CVaPEhJl0fuu85WAmn8qkj89TadD1wlEaeSUR8A=="
    }
  }
}
