apiVersion: v1
kind: Service
metadata:
  name: forum-service
  labels:
    app: forum-service
spec:
  selector:
    app: forum-service
  ports:
    - name: http-8080  # <-- THÊM ĐÚNG DÒNG NÀY 
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP