{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "auth-secret",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "auth-secret",
        "namespace": "default",
        "creationTimestamp": null
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "POSTGRES_DB": "AgCtHt3FtHVQrcP67GXQIezOPkkkcnbgM5vSqxHf97H2+kttpyp+ljXobNqyiCYzc29e6fBrMp7QamUsoEjwfSTr6npj5iNQry5VOc7ClW1UosDDn6zrPtafFWHGQethbtmwEe/DgH5uJAHqwS968C+JnaHsVMgPpIvt60OUCj52DrfLSQf4wbFJyls/vW5fBlG88AS65H6SHi2Pz/l5LmokiBk2cv4oVjp9mgcwl2Ui4dQ3r8tavYb17UZ+gV/Gh/wZ0CmAGij7apsT43rkughq7/XVtCARcfZi9c6vaZOpAjVfgQQxZtGYDJUJzWpK8/qssZ2t+cUrVcIv4pF3Bj0f89TPgujoSMe2sUiaAfR67aXGvngvt0tBGsVt+qGTLGry734cQqUnomYWv/9LbJB/eoGCIXOgQGdDsFlv14qFTpkdRzs6/eDCTzidnG39ET6wKY3jsS9AWlLiRwCHjZbed/0Qs8PEhn517yvsJ0VkUjsWYeMww7/smtFCFfn+3FT92H7Fuai3Mz+4N9gKeznMJS9rXV99g88127yXKKkyylGL3yxU5aW4LObz5JQIcpq6rdQmhP/a8j4eKtskOuQbRD2r8ZW5qxGOF3OAFNPCFivnK4zAgK3SosIuYKS2zeOHJEj1M5ABltxqUrGexIZDNYdb6XrmwA/Tzgddq6j7g/RMNnFEbLBpK8KEA0wutO/hTEwdkmVd",
      "POSTGRES_PASSWORD": "AgAnTWwfp0eftB4g9SrT4IYw1/1NLMQWZL5vrMP3Une8GDE1VqLNxuuL7ZllDUBAO81cPw/0q5i4/k4eqozmIbWQZSsSmx2a3aSw/SCC5lhPIPWu5xnqjSMRwOZ+1eJNM6sDcyrEBhT9Hw8QubP1+BQxMcgrR608vIDkar9RfzDOqoxWOHPYkJZJMM+eCkI5QsDPzVnsXujRCY5LaTuhz+FOM219iaLCQy+nO61dxSyiKCoBX/wSqxqmFTuBZhn0otLEggF109HajJhOCv0/G1tOEpS8GkLhEWT9PbVd4oQBcSG3PG19g29CjA5ZNRi3PKa0l2Ampte8nIpOJS7VDeHspUb9jdARSKNqqBgVgbsjCo+PQBWzoz464izINvc44pxd+zhuhpXj3M3MsetuOdnjUZy/sJolqShl50zkSIBEn5Sxlyno6Pt5GpcAkg25dsbujhvl21TjHmmPQW28KtiT71Y/CALnCm11lEPKBZIwevi7Z2FTnIHbNq7Cgg4RpwXDiPb0dvmimvrHU1+n1hC/no/9o3jT6MeboTMymzrNbDE/MyxtmMuJECPRRmcZ6xpEup6pUv1x8nCC8X//Fx2IeYbfrrMwAIlKEr+TFBUzSrtvaYDdN2wfgolQ+7qccuQz637JpxPbx0bz9gJMXtokiapvJyQ/LVjpfXosAnoGktkQBlOh5O6FS92d92LSnNFbuQKAN108Eg==",
      "POSTGRES_USER": "AgCBkOxbJtwMpN6eFJALbcui9ZY3Mm18laChFGuNuoHEWpmesfeUSAjmmz9WYGiXYzl7RcbD6KC8hHKuGtHba3v8dcfa26UU4gMOsA0b9Y2hV3YLOfh1UicI8WjYAXuqCuzprGox52OKOMcxYYxXMWOC0e1M9kPnuj/SRCuQaz4yW9y4EcVq0TqBOb6KIJUtOwp9LmTmv7c68QTMF7x6R+JqIB+Dr3z8Os6Y+v5HyWhjUQvOeYXjAJY7Gs5+YeDwr+t3mX0mXdWq4zTzUXfFtW0xcwMGjkQM9JUsrzv8bF46CBl7WfgStJGkDUbLk9d4aspReQ36ZGwgl+30UtFDr/VjrN0+qybvO59RSw2ssz9SUgJoLbuzzkFSdIOYGlYHCBuaEJehTeMptUQDsg1Haw+y5sgEdyfz/DNnDSNbbCHteLTHLC/oN0UeutyKQ74TXBbXZKZCNskqEynie1afAiSBa527e/8CWGEknmua1WFPHqWXftXUHWuU2uo7bCbhJO+zwhmheTu3iIMqgKt3pInTYPHyV6xyGF0CFqd9wnBh1l7OijtDktoXr2JVdeOoZ4uMk9RfBr3OXAnqWGDmksbP2xtdmnCiSklAGU65wT7H/Ls4kTX6/iN+M6ILmmTvCJNW4id3xqvM6+YddAqxND23WWGSqqV+Bu1mMiAjcT7D+iC973Blt0prWDR0AcP2lgzA3R3/uvs7kQ=="
    }
  }
}
