apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: docker.io/tuongndb1609/frontend
  newName: docker.io/tuongndb1609/frontend
  newTag: 50b91efaaf4fc233afb7bd63e2995919e05fa1e1
