apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: docker.io/tuongndb1609/frontend
  newName: docker.io/tuongndb1609/frontend
  newTag: adfe207c8772cf328aa16fd2dc29e5145b4bf647
