--
-- PostgreSQL database dump
--

\restrict z0WIDwc6LD63RdVdl8kPrNmKg4xr7kignocvcdh4DnjVAFwvK4tfd4fWlJLYs4u

-- Dumped from database version 17.9
-- Dumped by pg_dump version 17.9

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS users_pkey;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS ukr43af9ap4edm43mmtq01oddj6;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS uk6dotkott2kjsp8vw4d0m25fb7;
DROP TABLE IF EXISTS public.users;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    avatar_url character varying(1000)
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users (id, email, password, username, created_at, avatar_url) FROM stdin;
3	admin@pulseterminal.local	Aa123456	admin	\N	\N
4	tuongndb2@gmail.com	Aa123456	tuongndb2	\N	\N
5	test@example.com	123456	testuser	2026-03-28 15:07:24.153191	\N
6	23521750@gm.uit.edu.vn	Aa123456	tuongndb3	2026-03-28 15:08:34.444328	\N
18	trannam2020@traders.vn	Pass123456	trannam2020	2026-03-28 15:52:38.741317	\N
19	phamtuan.dev@analysts.vn	Pass123456	phamtuan_dev	2026-03-28 15:52:38.855634	\N
20	hoanglinh88@investors.vn	Pass123456	hoanglinh88	2026-03-28 15:52:38.968247	\N
21	vuhung.trader@traders.vn	Pass123456	vuhung_trader	2026-03-28 15:52:39.082228	\N
22	dangtuanabc@analysts.vn	Pass123456	dangtuanabc	2026-03-28 15:52:39.194688	\N
23	buidung.bull@traders.vn	Pass123456	buidung_bull	2026-03-28 15:52:39.308359	\N
24	duonghai.tech@traders.vn	Pass123456	duonghai_tech	2026-03-28 15:52:39.421552	\N
25	lybinhdev@analysts.vn	Pass123456	lybinhdev	2026-03-28 15:52:39.535034	\N
26	kieuulinh.fin@investors.vn	Pass123456	kieuulinh_fin	2026-03-28 15:52:39.647862	\N
17	nguyenhunga@traders.vn	Pass123456	nguyenhunga	2026-03-28 15:52:38.621642	/auth/avatar-files/nguyenhunga_1774689813724.png
1	tuongndb@gmail.com	Aa123456	tuongndb	\N	/auth/avatar-files/tuongndb_1774689951735.jpg
2	tuongndb1@gmail.com	Aa123456	tuongndb1	\N	/auth/avatar-files/tuongndb1_1774690849837.jpg
27	tram@gmail.com	123456	tramxinhgai	2026-03-28 17:17:38.73188	\N
\.


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_id_seq', 27, true);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict z0WIDwc6LD63RdVdl8kPrNmKg4xr7kignocvcdh4DnjVAFwvK4tfd4fWlJLYs4u

