apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - auth_db/deployment.yaml
  - auth_db/service.yaml
  - auth_db/pvc.yaml
  - auth_db/seal-secret-auth.yaml
  - forum_db/deployment.yaml
  - forum_db/service.yaml
  - forum_db/pvc.yaml
  - forum_db/seal-secret-forum.yaml
